import { useCallback,useEffect,useState } from 'react';
import { supabase } from '@/lib/supabase';
import { useAuth } from '@/contexts/AuthContext';
type Request = {id:string; proposed_amount:number; reason:string;status:string;resolution_note:string|null;created_at:string};
export default function CollectionRequests({jobId,canReview,onApplied}:{jobId:string;canReview:boolean;onApplied:()=>Promise<unknown>}) {
 const {profile}=useAuth();const [rows,setRows]=useState<Request[]>([]);const [amount,setAmount]=useState('');const [reason,setReason]=useState('');const [note,setNote]=useState('');const [error,setError]=useState<string|null>(null);const [busy,setBusy]=useState(false);
 const load=useCallback(async()=>{const {data,error}=await supabase.from('job_collection_requests').select('id,proposed_amount,reason,status,resolution_note,created_at').eq('job_id',jobId).order('created_at',{ascending:false});if(error)setError('Correction requests could not load.');else setRows(data??[]);},[jobId]);
 useEffect(()=>{void load();},[load]);
 const submit=async(e:React.FormEvent)=>{e.preventDefault();if(!profile||busy)return;setBusy(true);setError(null);const {error}=await supabase.from('job_collection_requests').insert({org_id:profile.org_id,job_id:jobId,requested_by:profile.id,proposed_amount:Number(amount),reason:reason.trim()});if(error)setError(error.code==='23505'?'Your correction request is already pending.':'The request could not save. Your values remain here.');else{setAmount('');setReason('');await load();}setBusy(false);};
 const review=async(id:string,apply:boolean)=>{if(busy)return;setBusy(true);setError(null);const {error}=await supabase.rpc('review_collection_request',{p_id:id,p_apply:apply,p_note:note});if(error)setError('The decision could not save. Add a note and retry.');else{setNote('');await load();if(apply)await onApplied();}setBusy(false);};
 return <details className="mt-3 border-t border-ink-700 pt-3"><summary className="cursor-pointer text-sm font-semibold text-brand-500">{canReview?'Collection correction requests':'Request a collection correction'}</summary><p className="my-2 text-xs text-ink-500">Owners and service managers can change Collect. Staff can request an exact correction here without receiving broader editing permissions.</p>{error&&<p role="alert" className="text-sm text-amber-600">{error}</p>}<form onSubmit={submit} className="space-y-2" data-unsaved={amount||reason?'true':undefined}><label className="block text-xs text-ink-400">Proposed amount<input required type="number" min="0" step="0.01" value={amount} onChange={e=>setAmount(e.target.value)} className="mt-1 w-full rounded border border-ink-700 bg-ink-950 p-2"/></label><label className="block text-xs text-ink-400">Reason / sale document<input required minLength={3} maxLength={2000} value={reason} onChange={e=>setReason(e.target.value)} className="mt-1 w-full rounded border border-ink-700 bg-ink-950 p-2"/></label><button disabled={busy} className="rounded bg-brand-500 px-3 py-2 text-sm text-white">Request correction</button></form>{canReview&&rows.some(r=>r.status==='pending')&&<label className="mt-3 block text-xs text-ink-400">Decision note<input value={note} onChange={e=>setNote(e.target.value)} className="mt-1 w-full rounded border border-ink-700 bg-ink-950 p-2"/></label>}{rows.map(row=><div key={row.id} className="mt-3 rounded-lg bg-ink-950 p-3 text-xs text-ink-400"><p className="font-semibold">${Number(row.proposed_amount).toLocaleString()} · {row.status}</p><p>{row.reason}</p>{row.resolution_note&&<p>Decision: {row.resolution_note}</p>}{canReview&&row.status==='pending'&&<div className="mt-2 flex gap-2"><button disabled={busy||note.trim().length<3} onClick={()=>void review(row.id,true)} className="rounded border border-ink-600 p-2">Apply amount</button><button disabled={busy||note.trim().length<3} onClick={()=>void review(row.id,false)} className="rounded border border-ink-600 p-2">Decline</button></div>}</div>)}</details>;
}
