import { centralInstant } from '@/agent/toolFactory';
import { useEffect,useState } from 'react';
import { useAuth } from '@/contexts/AuthContext';
import { supabase } from '@/lib/supabase';
import type { Job } from '@/types/database';
export default function ServiceExceptionReview({job,onSave,canEdit}:{job:Job;onSave:(changes:Partial<Job>)=>Promise<boolean>;canEdit:boolean}) {
 const {profile}=useAuth();const [team,setTeam]=useState<{id:string;first_name:string;last_name:string}[]>([]);const [owner,setOwner]=useState(job.exception_owner_id??'');const [reason,setReason]=useState(job.exception_reason??'');const [action,setAction]=useState(job.exception_next_action??'');const [due,setDue]=useState(job.exception_due_at?.slice(0,10)??'');const [busy,setBusy]=useState(false);const [editing,setEditing]=useState(false);
 useEffect(()=>{if(!profile)return;void supabase.from('profiles').select('id,first_name,last_name').eq('org_id',profile.org_id).then(({data})=>setTeam(data??[]));},[profile?.org_id,canEdit]);
 const pastHold=job.status==='Pending Confirm'&&job.job_type!=='To Do'&&job.scheduled_at&&new Date(job.scheduled_at)<new Date();
 return <section className="rounded-xl border border-ink-700 bg-ink-900 p-4 space-y-2"><h2 className="font-semibold text-ink-100">Dispatch review</h2>{pastHold&&<p role="status" className="text-sm text-amber-600">This hold is in the past. It is not a confirmed future appointment. Review its time before confirming.</p>}<p className="text-sm text-ink-400">{job.exception_next_action||'No review decision recorded.'}</p><p className="text-xs text-ink-500">Responsible: {team.find(p=>p.id===job.exception_owner_id)?`${team.find(p=>p.id===job.exception_owner_id)?.first_name} ${team.find(p=>p.id===job.exception_owner_id)?.last_name}`:'Not assigned'} · {job.exception_reason||'Reason not recorded'} · {job.exception_due_at?`Next review ${new Date(job.exception_due_at).toLocaleDateString()}`:'No review date'}</p>{canEdit&&<button className="text-sm text-brand-500" onClick={()=>{if(!editing){setOwner(job.exception_owner_id??'');setReason(job.exception_reason??'');setAction(job.exception_next_action??'');setDue(job.exception_due_at?.slice(0,10)??'');}setEditing(!editing);}}>{editing?'Cancel':'Record next action'}</button>}{canEdit&&editing&&<form data-unsaved="true" className="grid gap-3 sm:grid-cols-2" onSubmit={async e=>{e.preventDefault();setBusy(true);if(await onSave({exception_owner_id:owner,exception_reason:reason,exception_next_action:action,exception_due_at:centralInstant(`${due}T17:00`),exception_reviewed_at:new Date().toISOString()}))setEditing(false);setBusy(false);}}><label className="text-sm">Responsible teammate<select required value={owner} onChange={e=>setOwner(e.target.value)} className="block w-full rounded border border-ink-700 bg-ink-950 p-2"><option value="">Choose teammate</option>{team.map(p=><option key={p.id} value={p.id}>{p.first_name} {p.last_name}</option>)}</select></label><label className="text-sm">Reason<input required value={reason} onChange={e=>setReason(e.target.value)} className="block w-full rounded border border-ink-700 bg-ink-950 p-2"/></label><label className="text-sm">Next action<input required value={action} onChange={e=>setAction(e.target.value)} className="block w-full rounded border border-ink-700 bg-ink-950 p-2"/></label><label className="text-sm">Review date<input type="date" required value={due} onChange={e=>setDue(e.target.value)} className="block w-full rounded border border-ink-700 bg-ink-950 p-2"/></label><button disabled={busy} className="rounded bg-brand-500 px-3 py-2 text-sm text-white">Save dispatch review</button></form>}</section>;
}
